server:
  port: 8081
spring:
  application:
    name: liangheng
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: 192.168.202.133
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: guest
    password: guest
mybatis-plus:
  type-aliases-package: com.liangheng.entity # 别名扫描包
logging:
  level:
    com.liangheng: debug
